#!/bin/bash

set -e


jupyter nbextension install --py jupytext --user
jupyter labextension install jupyterlab-jupytext
jupyter labextension install @jupyter-widgets/jupyterlab-manager --minimize=False
jupyter lab build